import 'package:flutter/material.dart';
import '../../../data/repositories/championship_repository.dart';
import '../../../domain/models/championship.dart';

enum ChampionshipRegistrationState { initial, loading, success, error }

class ChampionshipRegistrationViewModel extends ChangeNotifier {
  final ChampionshipRepository _championshipRepository;

  ChampionshipRegistrationViewModel({
    required ChampionshipRepository championshipRepository,
  }) : _championshipRepository = championshipRepository;

  ChampionshipRegistrationState _state = ChampionshipRegistrationState.initial;
  ChampionshipRegistrationState get state => _state;

  String? _errorMessage;
  String? get errorMessage => _errorMessage;

  Future<void> registerChampionship({
    required String name,
    required String season,
    required String startDate,
    required String endDate,
  }) async {
    _state = ChampionshipRegistrationState.loading;
    notifyListeners();

    try {
      final championship = Championship(
        id: '', // ID will be generated by backend
        name: name,
        season: season,
        startDate: startDate,
        endDate: endDate,
      );

      await _championshipRepository.registerChampionship(championship);
      _state = ChampionshipRegistrationState.success;
    } catch (e) {
      _errorMessage = e.toString();
      _state = ChampionshipRegistrationState.error;
    } finally {
      notifyListeners();
    }
  }

  Future<void> updateChampionship({
    required String id,
    required String name,
    required String season,
    required String startDate,
    required String endDate,
  }) async {
    _state = ChampionshipRegistrationState.loading;
    notifyListeners();

    try {
      final championship = Championship(
        id: id,
        name: name,
        season: season,
        startDate: startDate,
        endDate: endDate,
      );

      await _championshipRepository.updateChampionship(championship);
      _state = ChampionshipRegistrationState.success;
    } catch (e) {
      _errorMessage = e.toString();
      _state = ChampionshipRegistrationState.error;
    } finally {
      notifyListeners();
    }
  }
}
