import 'package:flutter/material.dart';
import '../../../data/repositories/play_repository.dart';
import '../../../domain/models/play.dart';

enum GameManagementState { initial, loading, success, error }

class GameManagementViewModel extends ChangeNotifier {
  final PlayRepository _playRepository;

  GameManagementViewModel({required PlayRepository playRepository})
    : _playRepository = playRepository;

  GameManagementState _state = GameManagementState.initial;
  GameManagementState get state => _state;

  String? _errorMessage;
  String? get errorMessage => _errorMessage;

  List<Play> _recentPlays = [];
  List<Play> get recentPlays => _recentPlays;

  Future<void> loadPlays(String gameId) async {
    _state = GameManagementState.loading;
    notifyListeners();
    try {
      _recentPlays = await _playRepository.getPlaysByGameId(gameId);
      _state = GameManagementState.success;
    } catch (e) {
      _errorMessage = e.toString();
      _state = GameManagementState.error;
    } finally {
      notifyListeners();
    }
  }

  Future<void> registerPlay({
    required String gameId,
    required PlayType type,
    required String description,
    String? teamId,
    String? athleteId,
    required int quarter,
    required String time,
    required int down,
    required int yardsToGo,
    required int yardLine,
  }) async {
    _state = GameManagementState.loading;
    notifyListeners();

    try {
      final play = Play(
        id: '', // ID generated by backend
        gameId: gameId,
        type: type,
        description: description,
        teamId: teamId,
        athleteId: athleteId,
        quarter: quarter,
        time: time,
        down: down,
        yardsToGo: yardsToGo,
        yardLine: yardLine,
      );

      await _playRepository.registerPlay(play);
      await loadPlays(gameId); // Reload plays
      _state = GameManagementState.success;
    } catch (e) {
      _errorMessage = e.toString();
      _state = GameManagementState.error;
    } finally {
      notifyListeners();
    }
  }
}
