// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCU8s3QgOW_1fE0sds41Mzr6lAyAOpU9_k',
    appId: '1:854096625101:web:2f89ebe73659192f069884',
    messagingSenderId: '854096625101',
    projectId: 'sevenine-america',
    authDomain: 'sevenine-america.firebaseapp.com',
    storageBucket: 'sevenine-america.firebasestorage.app',
    measurementId: 'G-H25ZDNDS1T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUKQbb00GFWr2VXYwo2-GxkhUq6v3o6Yo',
    appId: '1:854096625101:android:0265bbc27aca2717069884',
    messagingSenderId: '854096625101',
    projectId: 'sevenine-america',
    storageBucket: 'sevenine-america.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_8jU_YcTyqrPRT5dZavOZtWUaJa_OiTQ',
    appId: '1:854096625101:ios:7c9a459b3081ace1069884',
    messagingSenderId: '854096625101',
    projectId: 'sevenine-america',
    storageBucket: 'sevenine-america.firebasestorage.app',
    iosBundleId: 'com.example.americaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_8jU_YcTyqrPRT5dZavOZtWUaJa_OiTQ',
    appId: '1:854096625101:ios:7c9a459b3081ace1069884',
    messagingSenderId: '854096625101',
    projectId: 'sevenine-america',
    storageBucket: 'sevenine-america.firebasestorage.app',
    iosBundleId: 'com.example.americaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCU8s3QgOW_1fE0sds41Mzr6lAyAOpU9_k',
    appId: '1:854096625101:web:c6c56d707d9813da069884',
    messagingSenderId: '854096625101',
    projectId: 'sevenine-america',
    authDomain: 'sevenine-america.firebaseapp.com',
    storageBucket: 'sevenine-america.firebasestorage.app',
    measurementId: 'G-VZ7VPCJ45N',
  );
}
